### ISSUE TITLE
Function singleTransfer returns test data - wrong variables

### ISSUE THREAD

**Issue by JacobZee** [comgate-payments/sdk-php#38]
https://github.com/comgate-payments/sdk-php/blob/c3578a5289ea00160830e6a07ce2645c9e918453/src/Client.php#L137C3-L137C63

Line 137 is: 
`$singleTransferRequest = new SingleTransferRequest(1, true);`

should be:
`$singleTransferRequest = new SingleTransferRequest($transferId, $test);`

Thank you

**Comment by iki-cz** [comment]
#39 resolved
