### ISSUE TITLE
v1.0.11 is not compatible with PHP < 8.2

### ISSUE THREAD

**Issue by mlutonsky** [comgate-payments/sdk-php#43]
Since version 1.0.11, the composer.json file of this package mistakenly declares compatibility with PHP version 7.3 and above:
```
        "php": "^7.3 || ^8.0",
```
However, this is incorrect because the v1.0.11 release includes major changes that use language constructs available only in PHP 8.2 and later. This results in total incompatibility with older PHP versions.

Exaple:
see src/Http/PsrStream.php at https://github.com/comgate-payments/sdk-php/commit/c9df5341cfcd05b458ec66aff7a349763b980810#diff-8009af9658d1818da064191a328e0afefcb91850d5017b9b290e534ae3deb75f - `null` return type in `detach()` method etc.

Please, update the composer.json file or fix the incomaptible files to reflect the correct PHP version requirements.
Thanks!

**Comment by iki-cz** [comment]
You are right. Resolved in v1.0.12. I'll add more checks.
