### ISSUE TITLE
Fatal error in PsrResponse

### ISSUE THREAD

**Issue by MT-111** [comgate-payments/sdk-php#47]
Hi,

on php version 8.2.20, I get following fatal:

PHP Fatal error:  Declaration of Comgate\SDK\Http\PsrResponse::withProtocolVersion(string $version): Psr\Http\Message\MessageInterface must be compatible with Psr\Http\Message\MessageInterface::withProtocolVersion($version) in /vendor/comgate/sdk/src/Http/PsrResponse.php on line 91

**Comment by iki-cz** [comment]
It should be resolved in v1.0.14. Can you check it? It was a problem with some version of PSR package. You have a different version propably and now SDK will require specific version.

**Comment by MT-111** [comment]
thank you, PSR reinstalled to newest version, after reinstalling comgate/sdk , I get following error:

PHP Fatal error:  Uncaught Error: Class "GuzzleHttp\Psr7\Query" not found in /vendor/comgate/sdk/src/Entity/Response/PaymentCreateResponse.php:28

"composer require comgate/sdk" install only these packages (with no warning/error):
  - Locking comgate/sdk (v1.0.14)
  - Locking psr/log (3.0.0)
  - Installing psr/log (3.0.0): Extracting archive
  - Installing comgate/sdk (v1.0.14): Extracting archivee-dev)

**Comment by MT-111** [comment]
installed guzzle separately and its ok
