### ISSUE TITLE
Param chargeUnregulatedCardFees is not set from v1.0.19

### ISSUE THREAD

**Issue by majun** [comgate-payments/sdk-php#60]
Although create payment request works with version 1.0.18, it returns error with version 1.0.19, on call `\Comgate\SDK\Client::createPayment`:
```
Param chargeUnregulatedCardFees is not set
```
We use Composer constraint `"comgate/sdk": "^1.0.13"`, because a minor or patch version should be backward compatible, as documentation says:

> Given a version number MAJOR.MINOR.PATCH, increment the:
    MAJOR version when you make incompatible API changes
    MINOR version when you add functionality in a backward compatible manner
    PATCH version when you make backward compatible bug fixes

**Comment by majun** [comment]
cc @sirluky

**Comment by sirluky** [comment]
Should be Minor, release process currently support only patch versions.

Fix is now released as patch 1.0.20. Sorry for inconvinience, thank for reporting the issue.
